//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLEFACTURAs = new HashSet<DETALLEFACTURA>();
        }
    
        public int IDFACTURA { get; set; }
        public string NUMEROFACTURA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string TIPODEPAGO { get; set; }
        public string DOCUMENTOCLIENTE { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public int SUBTOTAL { get; set; }
        public int DESCUENTO { get; set; }
        public int IVA { get; set; }
        public int TOTALDESCUENTO { get; set; }
        public int TOTALIMPUESTO { get; set; }
        public int TOTAL { get; set; }
    
        public virtual ICollection<DETALLEFACTURA> DETALLEFACTURAs { get; set; }
    }
}
