//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLEFACTURAs = new HashSet<DETALLEFACTURA>();
        }
    
        public int IDPRODUCTO { get; set; }
        public string PRODUCTO1 { get; set; }
    
        public virtual ICollection<DETALLEFACTURA> DETALLEFACTURAs { get; set; }
    }
}
